services:
  nest-app:
    build: .
    container_name: nest_tutorial_api
    restart: always
    ports:
      - '4000:3001' # Máy ngoài truy cập port 4000, trong Docker chạy 3001
    env_file:
      - .env
