services:
  nest-app:
    build: .
    container_name: nest_tutorial_api
    restart: always
    ports:
      - '7320:3001' # Máy ngoài truy cập port 732005, trong Docker chạy 3001
    env_file:
      - .env
