name: Deploy NestJS Project
on:
  push:
    branches:
      - feat/NinedevNestJs

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 103.161.16.77
          username: root
          port: 26266
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            TARGET_DIR="/var/www/nest-tutorial-app"
            rm -rf $TARGET_DIR
            mkdir -p $TARGET_DIR
            cd $TARGET_DIR
            git clone -b feat/NinedevNestJs https://github.com/Trhgam/self-taught-NestJs-be.git .
            cd nest-tutorial
            docker compose down || true
            docker compose up -d --build